# Site settings
title: Jeb's Notes
header-img: img/home-bg.png
email: jebediahelliott@gmail.com
copyright_name: jebediahelliott
description: > # this means to ignore newlines until "baseurl:"
  Some notes on what I learn while coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jebediahelliott
learn_profile: jebediahelliott
email_username: jebediahelliott@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
